/// <reference types="vitest" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    testTimeout: 10000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.{js,jsx,ts,tsx}'],
      exclude: [
        'src/**/*.d.ts',
        'src/main.tsx',
        'src/vite-env.d.ts',
        'src/App.tsx',
        'src/components/AboutSection.tsx',
        'src/components/ChatBot.tsx',
        'src/components/ContactSection.tsx',
        'src/components/ExperienceSection.tsx',
        'src/components/Footer.tsx',
        'src/components/about/CompaniesWorked.tsx',
        'src/components/about/EducationSection.tsx',
        'src/components/about/KeyAchievements.tsx',
        'src/components/chatbot/ChatButton.tsx',
        'src/components/chatbot/ChatHeader.tsx',
        'src/components/chatbot/ChatInput.tsx',
        'src/components/chatbot/chatbot-data.ts',
        'src/components/contact/ContactInfo.tsx',
        'src/components/experience/TechnicalSkills.tsx',
        'src/components/ui/accordion.tsx',
        'src/components/ui/avatar.tsx',
        'src/components/ui/button-utils.ts',
        'src/components/ui/button.tsx',
        'src/components/ui/card.tsx',
        'src/components/ui/collapsible.tsx',
        'src/components/ui/dialog.tsx',
        'src/components/ui/input.tsx',
        'src/components/ui/loading-spinner.tsx',
        'src/components/ui/skip-link.tsx',
        'src/components/ui/sonner.tsx',
        'src/components/ui/tabs.tsx',
        'src/components/ui/textarea.tsx',
        'src/components/ui/tooltip.tsx',
        'src/config/companies.ts',
        'src/config/company-icons.tsx',
        'src/config/contact.ts',
        'src/config/education.ts',
        'src/context/theme-context.ts',
        'src/lib/utils.ts',
        'src/pages/Index.tsx',
        'src/pages/NotFound.tsx',
        'src/test/test-providers.tsx',
        'src/test/test-render.ts',
        'src/test/test-utils.ts',
      ],
    },
  },
}); 